Rewrite and clean code, add references.
Quest-maker-team/quest-maker pull request #68
Opened 2022-03-15 17:59 UTC by AleksandrShvartz

2022-03-17 21:34 UTC, IlyaP01 requested changes

2022-03-17 21:34 UTC, IlyaP01 commented on website/questmaker/schema.sql
> +--\connect questmaker;
If think, it's better to delete comments in lines 4, 5

2022-03-17 21:34 UTC, IlyaP01 commented on website/questmaker/schema.sql
> +    email CHARACTER VARYING(100)UNIQUE NOT NULL,
(100) UNIQUE (add space))

2022-03-17 21:34 UTC, IlyaP01 commented on website/questmaker/schema.sql
> +    name CHARACTER VARYING(100)  NOT NULL,
two spaces before NOT

2022-03-17 21:34 UTC, IlyaP01 commented on website/questmaker/schema.sql
> +	q_type_name CHARACTER VARYING(100) UNIQUE NOT NULL
Extra tab

2022-03-17 21:34 UTC, IlyaP01 commented on website/questmaker/schema.sql
> +	points REAL NOT NULL DEFAULT 0.0,
Extra tab on 107, 108

2022-03-17 21:34 UTC, IlyaP01 commented on website/questmaker/schema.sql
> +	next_question_id INTEGER REFERENCES questions (question_id)ON DELETE CASCADE
Add space before ON

2022-03-17 21:34 UTC, IlyaP01 commented on website/questmaker/schema.sql
> +    place_id INTEGER REFERENCES places (place_id) ON DELETE CASCADE,
NOT NULL

2022-03-17 21:34 UTC, IlyaP01 commented on website/questmaker/schema.sql
> +	next_question_id INTEGER REFERENCES questions (question_id)ON DELETE CASCADE
Remove extra tab and add space before ON

2022-03-17 21:34 UTC, IlyaP01 commented on website/questmaker/schema.sql
> +);
Remove extra tabs in 134-137 lines

2022-03-17 21:36 UTC, IlyaP01 commented on website/questmaker/schema.sql
> +    place_id INTEGER REFERENCES places (place_id) ON DELETE CASCADE,
place_id NOT NULL

2022-03-18 09:35 UTC, IlyaP01 approved these changes

2022-03-18 09:38 UTC, gchevykalov approved these changes

2022-03-18 09:40 UTC, merged